// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20230626035140_0002")]
    partial class _0002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .IsRequired()
                        .HasColumnName("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnName("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("user_name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("ix_user_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasName("ix_user_user_name");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf93d96c-dc91-4e33-9c34-63a8349d1def"),
                            CreateAt = new DateTime(2023, 6, 26, 0, 51, 39, 966, DateTimeKind.Local).AddTicks(2008),
                            Email = "admin@test.com",
                            Password = "$2a$11$Fi.g6aTNlZyh.6.n05PDM.Jj62cmm10ANhPe.3I9r/r.kM8HqNzKS",
                            UpdateAt = new DateTime(2023, 6, 26, 0, 51, 39, 967, DateTimeKind.Local).AddTicks(2621),
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
